<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>PaymentHub</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PaymentHub.Application.Contracts\PaymentHub.Application.Contracts.csproj" />
    <ProjectReference Include="..\PaymentHub.Domain\PaymentHub.Domain.csproj" />
  </ItemGroup>

</Project>